// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PriceCalculatorController from "./price_calculator_controller"
application.register("price-calculator", PriceCalculatorController)

import SaleCalculatorController from "./sale_calculator_controller"
application.register("sale-calculator", SaleCalculatorController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import SettingFormController from "./setting_form_controller"
application.register("setting-form", SettingFormController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)
